apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: ca-injector.microcumul.us
webhooks:
- name: ca-injector.microcumul.us
  admissionReviewVersions:
  - v1
  sideEffects: NoneOnDryRun
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
  failurePolicy: Ignore
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNaekNDQWUyZ0F3SUJBZ0lVYjRaZHlMb1ovL2lEVStuNTh2YWFBZjdEclFZd0NnWUlLb1pJemowRUF3TXcKY3pFTE1Ba0dBMVVFQmhNQ1ZWTXhFREFPQmdOVkJBZ1RCMEZ5YVhwdmJtRXhFVEFQQmdOVkJBY1RDRU5vWVc1awpiR1Z5TVJVd0V3WURWUVFLRXd4TmFXTnliMk4xYlhWc2RYTXhEekFOQmdOVkJBc1RCakl3TWpGRFFURVhNQlVHCkExVUVBeE1PTWpBeU1TQlRkSFZoY25RZ1EwRXdIaGNOTWpFd05URTNNVGMxTkRBd1doY05Nall3TlRFMk1UYzEKTkRBd1dqQnpNUXN3Q1FZRFZRUUdFd0pWVXpFUU1BNEdBMVVFQ0JNSFFYSnBlbTl1WVRFUk1BOEdBMVVFQnhNSQpRMmhoYm1Sc1pYSXhGVEFUQmdOVkJBb1RERTFwWTNKdlkzVnRkV3gxY3pFUE1BMEdBMVVFQ3hNR01qQXlNVU5CCk1SY3dGUVlEVlFRREV3NHlNREl4SUZOMGRXRnlkQ0JEUVRCMk1CQUdCeXFHU000OUFnRUdCU3VCQkFBaUEySUEKQk0yWUJjTHo1TklDQzZKUFY4U1hUbUZ1L0dTM3duUzF3UVV3QmFvbW1MQ3ZzT202cE1LTytGVHZwbzNCdzNLWQozb01WcDJJalREcyszSXZoZnMzbitoblI1b090U0ZOQlo0S1I3TFd0VXROdmEzM01qS2ZMUnJJVENCdzNlWWV3CmQ2TkNNRUF3RGdZRFZSMFBBUUgvQkFRREFnRUdNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUUKRk5jOW9idFpJcUdvQmhyeDRGTjhzREFXRnFLNE1Bb0dDQ3FHU000OUJBTURBMmdBTUdVQ01RREVUL0RWcUk5QQo2VWhDZ0tRcHlma3lWQnlxdHEvZGsyTzhRendZNWM1cWRZTkpHYzhUVU9OMnhsS0FOQ1owWWFNQ01IdWs5TldnCmczQ1l2YzJvSmcyTjR4dnFIMzFuQTZBU3FDbllKL1ZRT1ZmYmNScjRQNCt3aVQ3TTcxbHlrUnQvMnc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    service:
      namespace: admission
      name: ca-injector
      path: /pods
  namespaceSelector: {}
    # matchExpressions:
    # - key: control-plane
    #   operator: DoesNotExist
---
