{{- if and .Values.networkPolicy.enabled (eq .Values.networkPolicy.flavor "cilium") }}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ template "ca-injector.fullname" . }}
  namespace: {{ template "ca-injector.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ template "ca-injector.name" . }}
    {{- include "ca-injector.labels" . | nindent 4 }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: {{ template "ca-injector.name" . }}
      {{- include "ca-injector.labels" $ | nindent 6 }}
  egress:
  {{- if and .Values.networkPolicy.cilium .Values.networkPolicy.cilium.egress }}
    {{ toYaml .Values.networkPolicy.cilium.egress | nindent 6 }}
  {{- else }}
  - toEntities:
    - kube-apiserver
  {{- end }}
  ingress:
  - toPorts:
    - ports:
      {{- if .Values.tls.enabled }}
      - port: {{ .Values.tls.internalPort | quote }}
      {{- else }}
      - port: "8080"
      {{- end }}
        protocol: "TCP"
      rules:
        http:
        - method: "GET"
          path: "/metrics"
{{- end }}
