{{- if and .Values.networkPolicy.enabled (eq .Values.networkPolicy.flavor "cilium") }}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ include "ca-injector.fullname" . }}
  namespace: {{ include "ca-injector.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "ca-injector.name" . }}
    {{- include "ca-injector.labels" . | indent 4 }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ca-injector.name" . }}
      {{- include "ca-injector.labels" . | indent 6 }}
  egress:
  {{- if and .Values.networkPolicy.cilium .Values.networkPolicy.cilium.egress }}
    {{- toYaml .Values.networkPolicy.cilium.egress | nindent 6 }}
  {{- else }}
  - toEntities:
    - kube-apiserver
  {{- end }}
  ingress:
  - toPorts:
    - ports:
      - port: {{ .Values.internalPort | quote }}
        protocol: "TCP"
      rules:
        http:
        - method: "GET"
          path: "/metrics"
{{- end }}
