apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "ca-injector.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "ca-injector.name" . }}
{{ include "ca-injector.labels" . | indent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - read
  - list
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
