apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ca-injector.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "ca-injector.name" . }}
    {{- include "ca-injector.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ca-injector.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "ca-injector.serviceAccountName" . }}
  namespace: {{ include "ca-injector.namespace" . }}
