apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ca-injector.fullname" . }}
  namespace: {{ include "ca-injector.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "ca-injector.name" . }}
    {{- include "ca-injector.labels" . | indent 4 }}
    {{- if .Values.labels }}
    {{- toYaml .Values.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.annotations }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ca-injector.name" . }}
      app.kubernetes.io/instance: {{ $.Release.Name | quote }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "ca-injector.name" . }}
        {{- include "ca-injector.labels" . | indent 8 }}
        {{- if .Values.podLabels }}
        {{- toYaml .Values.podLabels | nindent 8 }}
        {{- end }}
      {{- if .Values.podAnnotations }}
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- include "ca-injector.imagePullSecrets" . | indent 8 }}
      {{- end }}
      containers:
        - name: {{ include "ca-injector.name" . }}
          {{- if .Values.image.sha }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}@sha256:{{ .Values.image.sha }}"
          {{- else }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          {{- end }}
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          env:
            {{- if .Values.caBundle.configMap }}
            - name: CAINJECTOR_CABUNDLE_CONFIGMAP
              value: {{ .Values.caBundle.configMap }}
            {{- end }}
            {{- if .Values.caBundle.crt }}
            - name: CAINJECTOR_CABUNDLE_CRT
              value: {{ .Values.caBundle.crt }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.internalPort }}
              name: https
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          volumeMounts:
            - name: tls-secret
              mountPath: /cert
              readOnly: true
      volumes:
        - name: tls-secret
          secret:
            defaultMode: 420
            secretName: {{ include "ca-injector.fullname" . }}-admission
      {{- with .Values.dnsConfig }}
      dnsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.securityContext }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ca-injector.serviceAccountName" . }}
      {{- if .Values.hostNetwork }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
