{{- if and .Values.networkPolicy.enabled (eq .Values.networkPolicy.flavor "kubernetes") }}
apiVersion: {{ include "ca-injector.networkPolicy.apiVersion" . }}
kind: NetworkPolicy
metadata:
  name: {{ include "ca-injector.fullname" . }}
  namespace: {{ include "ca-injector.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "ca-injector.name" . }}
    {{- include "ca-injector.labels" . | indent 4 }}
spec:
  egress: 
  - {}
  ingress:
  - ports:
    - port: {{ .Values.internalPort }}
  policyTypes:
  - Egress
  - Ingress
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ca-injector.name" . }}
      app.kubernetes.io/instance: {{ $.Release.Name | quote }}
{{- end }}
