{{- if and .Values.networkPolicy.enabled (eq .Values.networkPolicy.flavor "kubernetes") }}
apiVersion: {{ template "ca-injector.networkPolicy.apiVersion" . }}
kind: NetworkPolicy
metadata:
  name: {{ template "ca-injector.fullname" . }}
  namespace: {{ template "ca-injector.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ template "ca-injector.name" . }}
    {{- include "ca-injector.labels" . | nindent 4 }}
spec:
  egress: 
    - {}
  ingress:
    - ports:
      {{- if .Values.tls.enabled }}
      - port: {{ .Values.tls.internalPort }}
      {{- else }}
      - port: 8080
      {{- end }}
  policyTypes:
    - Egress
    - Ingress
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ template "ca-injector.name" . }}
      app.kubernetes.io/instance: {{ $.Release.Name | quote }}
{{- end }}
