apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ca-injector.fullname" . }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - read
  - list
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ca-injector.fullname" . }} 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ca-injector.fullname" . }} 
subjects:
- kind: ServiceAccount 
  name: {{ include "ca-injector.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
