apiVersion: v1
kind: Service
metadata:
  name: {{ include "ca-injector.fullname" . }}
  namespace: {{ include "ca-injector.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "ca-injector.name" . }}
    {{- include "ca-injector.labels" . | indent 4 }}
  {{- if .Values.service.labels }}
    {{- toYaml .Values.service.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  {{- if .Values.service.externalIPs }}
  externalIPs:
    {{- toYaml .Values.service.externalIPs | nindent 4 }}
  {{- end }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- range $cidr := .Values.service.loadBalancerSourceRanges }}
  - {{ $cidr }}
  {{- end }}
  {{- end }}
  {{- if ne .Values.service.type "ClusterIP" }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  ports:
  - name: https
    {{- if eq .Values.service.type "NodePort"}}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
    port: 443
    targetPort: https
  selector:
    app.kubernetes.io/name: {{ include "ca-injector.name" . }}
    app.kubernetes.io/instance: {{ $.Release.Name | quote }}
  type: "{{ .Values.service.type }}"
