{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "ca-injector.serviceAccountName" . }}
  namespace: {{ template "ca-injector.namespace" . }}
  labels:
{{ include "ca-injector.labels" . | indent 4 }}
{{- if .Values.imagePullSecrets }}
imagePullSecrets:
{{ include "ca-injector.imagePullSecrets" . | trim | indent 2 }}
{{- end }}
{{- end }}
