{{- if and .Values.admissionWebhook.patch.enabled (not .Values.admissionWebhook.certManager.enabled) }}
apiVersion: batch/v1
kind: Job
metadata:
  name:  {{ include "ca-injector.fullname" . }}-admission-create
  namespace: {{ include "ca-injector.namespace" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    {{- with .Values.admissionWebhook.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    app.kubernetes.io/name: {{ include "ca-injector.name" . }}-admission-create
    {{- include "ca-injector.labels" . | indent 4 }}
spec:
  {{- if .Capabilities.APIVersions.Has "batch/v1alpha1" }}
  # Alpha feature since k8s 1.12
  ttlSecondsAfterFinished: 0
  {{- end }}
  template:
    metadata:
      name:  {{ include "ca-injector.fullname" . }}-admission-create
      {{- with .Values.admissionWebhook.patch.podAnnotations }}
      annotations:
        {{- toYaml .  | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: {{ include "ca-injector.name" . }}-admission-create
        {{- include "ca-injector.labels" . | indent 8 }}
    spec:
      {{- if .Values.admissionWebhook.patch.priorityClassName }}
      priorityClassName: {{ .Values.admissionWebhook.patch.priorityClassName }}
      {{- end }}
      containers:
        - name: create
          {{- if .Values.admissionWebhook.patch.image.sha }}
          image: {{ .Values.admissionWebhook.patch.image.registry }}/{{ .Values.admissionWebhook.patch.image.repository }}:{{ .Values.admissionWebhook.patch.image.tag }}@sha256:{{ .Values.admissionWebhook.patch.image.sha }}
          {{- else }}
          image: {{ .Values.admissionWebhook.patch.image.registry }}/{{ .Values.admissionWebhook.patch.image.repository }}:{{ .Values.admissionWebhook.patch.image.tag }}
          {{- end }}
          imagePullPolicy: {{ .Values.admissionWebhook.patch.image.pullPolicy }}
          args:
            - create
            - --host={{ include "ca-injector.fullname" . }},{{ include "ca-injector.fullname" . }}.{{ include "ca-injector.namespace" . }}.svc
            - --namespace={{ include "ca-injector.namespace" . }}
            - --secret-name={{ include "ca-injector.fullname" . }}-admission
            - --key-name=tls.key
            - --cert-name=tls.crt
          {{- with .Values.admissionWebhook.createSecretJob }}
          securityContext:
            {{- toYaml .securityContext | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.admissionWebhook.patch.resources | nindent 12 }}
      restartPolicy: OnFailure
      serviceAccountName: {{ include "ca-injector.fullname" . }}-admission
      {{- with .Values.admissionWebhook.patch.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.admissionWebhook.patch.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.admissionWebhook.patch.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.admissionWebhook.patch.securityContext }}
      securityContext:
        {{- toYaml .Values.admissionWebhook.patch.securityContext | nindent 8 }}
      {{- end }}
{{- end }}
