{{- if and .Values.admissionWebhook.patch.enabled (not .Values.admissionWebhook.certManager.enabled) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name:  {{ include "ca-injector.fullname" . }}-admission
  namespace: {{ include "ca-injector.namespace" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app.kubernetes.io/name: {{ include "ca-injector.name" . }}-admission
    {{- include "ca-injector.labels" . | indent 4 }}
{{- if .Values.imagePullSecrets }}
imagePullSecrets:
{{ include "ca-injector.imagePullSecrets" . | trim | indent 2 }}
{{- end }}
{{- end }}
