name: Bump version

on:
  pull_request:
    branches:
      - 'main'
      - 'task/fix-docker-tags'

    types:
      - closed

permissions:
  contents: write
  pull-requests: write

jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
      - name: Install semver
        run: |
          pip install semver
      - uses: actions/checkout@v4
      - name: Bump helm version
        if: |
          (github.event.pull_request.merged == true) &&
          (contains(github.event.pull_request.labels.*.name, 'helm-patch') ||
          contains(github.event.pull_request.labels.*.name, 'helm-minor') ||
          contains(github.event.pull_request.labels.*.name, 'helm-major'))
        run: |
          label_names='${{ toJSON(github.event.pull_request.labels) }}'
          relevant_labels=$(echo $label_names |  jq '[.[] | select((.name == "helm-patch") or (.name == "helm-minor") or (.name == "helm-major"))]')
          length=$(echo $relevant_labels | jq 'length')
          if [ $length != 1 ]; then echo "More than one or none label has been defined. Exiting." && exit 1;fi

          version_bump_type=$(echo $relevant_labels | jq -r '.[] | .name')
          version_bump_type=${version_bump#"helm-"}

          current_version=$(sed -n -e 's/^.*version: //p' charts/ca-injector/Chart.yaml)
          new_version=$(python -m semver bump -i $version_bump_type $current_version)

          sed -i "s/version:.*/version: $new_version/g" charts/ca-injector/Chart.yaml
      - name: Bump App version
        if: |
          (github.event.pull_request.merged == true) &&
          (contains(github.event.pull_request.labels.*.name, 'app-patch') ||
          contains(github.event.pull_request.labels.*.name, 'app-minor') ||
          contains(github.event.pull_request.labels.*.name, 'app-major'))
        run: |
          label_names='${{ toJSON(github.event.pull_request.labels) }}'
          relevant_labels=$(echo $label_names |  jq '[.[] | select((.name == "app-patch") or (.name == "app-minor") or (.name == "app-major"))]')
          length=$(echo $relevant_labels | jq 'length')
          if [ $length != 1 ]; then echo "More than one or none label has been defined. Exiting." && exit 1;fi
          version_bump_type=$(echo $relevant_labels | jq -r '.[] | .name')
          version_bump_type=${version_bump#"app-"}

          current_version=$(sed -n -e 's/^.*appVersion: //p' charts/ca-injector/Chart.yaml)
          new_version=$(python -m semver bump -i $version_bump_type $current_version)

          sed -i "s/appVersion:.*/appVersion: $new_version/g" charts/ca-injector/Chart.yaml

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: 'Bump version'
