name: Bump helm app version

on:
  push:
    branches:
      - "main"
    tags:
      - "v?[0-9]+.[0-9]+.[0-9]+*"

permissions:
  contents: write
  pull-requests: write

jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bump appVersion
        run: |
          sed -i 's/appVersion:.*/appVersion: ${{ github.ref_name }}/g' charts/ca-injector/Chart.yaml
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: "Add app version ${{ github.ref_name }}"
          base: main
